module BBBServer {
    interface Server {
        string led_on(in string pin_led,
                in string pin_pwm,
                in string pin_enable,
                in string name,
                in boolean simulated,
                in float exp_time,
                in long brightness);

        string led_off(in string pin_led,
                in string pin_pwm,
                in string pin_enable,
                in string name,
                in boolean simulated,
                in float exp_time,
                in long brightness);

        string motor_move(in string name,
                in string pin_dir, 
                in string pin_step, 
                in string pin_sleep, 
                in string pin_opto1, 
                in string pin_opto2, 
                in boolean simulated, 
                in long direction,
                in long velocity, 
                in long steps, 
                in long vr_init, 
                in long vr_end, 
                in string cur_pos);

        string motor_move_skip_sensor(in string name, 
                in string pin_dir, 
                in string pin_step, 
                in string pin_sleep, 
                in string pin_opto1, 
                in string pin_opto2, 
                in boolean simulated, 
                in long direction,
                in long velocity, 
                in long steps, 
                in long vr_init, 
                in long vr_end, 
                in string cur_pos);

    };
};


