module BBBServer {
    typedef sequence<string> list;

    interface Server {
        string led_on(in string pin_led,
                in string pin_pwm,
                in string pin_enable,
                in string name,
                in boolean simulated,
                in float exp_time,
                in long brightness);

        string led_off(in string pin_led,
                in string pin_pwm,
                in string pin_enable,
                in string name,
                in boolean simulated,
                in float exp_time,
                in long brightness);

        long motor_move(in string name,
                in string direction,
                in long velocity, 
                in long steps, 
                in long cur_pos,
                in long cmd_pos);

        long motor_move_skip_sensor(in string name, 
                in string direction,
                in long velocity, 
                in long steps, 
                in long cur_pos,
                in long cmd_pos);

        long get_motor_cur_pos(in string name); 
        long get_motor_cmd_pos(in string name); 

        list get_stars_status_keys();
        list get_stars_status_value(in string key);

    };
};


