# DO NOT EDIT THIS FILE!
#
# Python module BBBServer generated by omniidl

import omniORB
omniORB.updateModule("BBBServer")

# ** 1. Stub files contributing to this module
import bbbserver_idl

# ** 2. Sub-modules

# ** 3. End
