#!/usr/bin/env python

import Adafruit_BBIO.GPIO as GPIO
import Adafruit_BBIO.PWM as PWM
from time import sleep
import sys

def turn_on_gpio(pin):
    GPIO.setup(pin, GPIO.OUT)
    GPIO.output(pin,GPIO.HIGH)
    print sys._getframe().f_code.co_name,
    print(' '+pin)
    raw_input('press a key to continue')

def turn_off_gpio(pin):
    GPIO.setup(pin, GPIO.OUT)
    GPIO.output(pin,GPIO.LOW)
    print sys._getframe().f_code.co_name,
    print(' '+pin)
    raw_input('press a key to continue')

def turn_on_pwm(pin):
    PWM.start(pin, 50)
    PWM.set_duty_cycle(pin, 25.5)
    PWM.set_frequency(pin, 10)
    print sys._getframe().f_code.co_name,
    print(' '+pin)
    raw_input('press a key to continue')

def turn_off_pwm(pin):
    PWM.stop(pin)
    PWM.cleanup()
    print sys._getframe().f_code.co_name,
    print(' '+pin)
    raw_input('press a key to continue')

if __name__ == '__main__':
    turn_off_gpio("P8_3")
    turn_off_gpio("P8_4")
    turn_off_gpio("P8_5")
    turn_off_gpio("P8_6")
    turn_off_gpio("P8_7")
    turn_off_gpio("P8_8")
    turn_off_gpio("P8_9")
    turn_off_gpio("P8_10")
    turn_off_gpio("P8_11")
    turn_off_gpio("P8_12")
    turn_off_gpio("P8_13")
    turn_off_gpio("P8_14")
    turn_off_gpio("P8_15")
    turn_off_gpio("P8_16")
    turn_off_gpio("P8_17")
    turn_off_gpio("P8_18")
    turn_off_gpio("P8_18")
    turn_off_gpio("P8_19")
    turn_off_gpio("P8_20")
    turn_off_gpio("P8_20")
    turn_off_gpio("P8_21")
    turn_off_gpio("P8_22")
    turn_off_gpio("P8_23")
    turn_off_gpio("P8_24")
    turn_off_gpio("P8_25")
    turn_off_gpio("P8_26")
    turn_off_gpio("P8_27")
    turn_off_gpio("P8_28")
    turn_off_gpio("P8_29")
    turn_off_gpio("P8_30")
    turn_off_gpio("P8_31")
    turn_off_gpio("P8_32")
    turn_off_gpio("P8_33")
    turn_off_gpio("P8_34")
    turn_off_gpio("P8_35")
    turn_off_gpio("P8_36")
    turn_off_gpio("P8_37")
    turn_off_gpio("P8_38")
    turn_off_gpio("P8_39")
    turn_off_gpio("P8_40")
    turn_off_gpio("P8_41")
    turn_off_gpio("P8_42")
    turn_off_gpio("P8_43")
    turn_off_gpio("P8_44")
    turn_off_gpio("P8_45")
    turn_off_gpio("P8_46")
    turn_off_gpio("P9_1")
    turn_off_gpio("P9_2")
#    turn_off_gpio("P9_3")
#    turn_off_gpio("P9_4")
#    turn_off_gpio("P9_5")
#    turn_off_gpio("P9_6")
#    turn_off_gpio("P9_7")
#    turn_off_gpio("P9_8")
#    turn_off_gpio("P9_9")
#    turn_off_gpio("P9_10")
    turn_off_gpio("P9_11")
    turn_off_gpio("P9_12")
    turn_off_gpio("P9_13")
    turn_off_gpio("P9_14")
    turn_off_gpio("P9_15")
    turn_off_gpio("P9_16")
    turn_off_gpio("P9_17")
    turn_off_gpio("P9_18")
    turn_off_gpio("P9_18")
    turn_off_gpio("P9_19")
    turn_off_gpio("P9_20")
    turn_off_gpio("P9_20")
    turn_off_gpio("P9_21")
    turn_off_gpio("P9_22")
    turn_off_gpio("P9_23")
    turn_off_gpio("P9_24")
    turn_off_gpio("P9_25")
    turn_off_gpio("P9_26")
    turn_off_gpio("P9_27")
    turn_off_gpio("P9_28")
    turn_off_gpio("P9_29")
    turn_off_gpio("P9_30")
    turn_off_gpio("P9_31")
    turn_off_gpio("P9_32")
    turn_off_gpio("P9_33")
    turn_off_gpio("P9_34")
    turn_off_gpio("P9_35")
    turn_off_gpio("P9_36")
    turn_off_gpio("P9_37")
    turn_off_gpio("P9_38")
    turn_off_gpio("P9_39")
    turn_off_gpio("P9_40")
    turn_off_gpio("P9_41")
    turn_off_gpio("P9_42")
    turn_off_gpio("P9_43")
    turn_off_gpio("P9_44")
    turn_off_gpio("P9_45")
    turn_off_gpio("P9_46")
    print "finish to turn off"
